### ISSUE TITLE
prize data

### ISSUE THREAD

**Issue by pparshakov** [ReagentX/HLTV-Scraper#2]
This is not really an issue, it is a request. Could you please add the information on prize money and its distribution across the ranks (like this https://www.hltv.org/events/3016/eleague-csgo-premier-2017) for the events?

Thank you!

**Comment by ReagentX** [comment]
Partially added in [f3d8117](https://github.com/ReagentX/HLTV-Scraper/commit/f3d811714f236049e744cb96d0c1d3e03deb0118). Will scrape the team results in a future update.

**Comment by pparshakov** [comment]
Thank you! Will wait for the update.

**Comment by ReagentX** [comment]
Added support in [f9f9258](https://github.com/ReagentX/HLTV-Scraper/commit/f9f9258149bed1d8828f63f4cdd35da4d5581f88). I uploaded the CSVs in [69f72d4e](https://github.com/ReagentX/HLTV-Scraper/commit/69f72d4ec9231e052348207af0e86c51f6d2bfbe).

**Comment by pparshakov** [comment]
Thank you!
