### ISSUE TITLE
Tried to Build on Ubuntu 16.04 VM got error

### ISSUE THREAD

**Issue by CodingAkiraZi** [ReagentX/HLTV-Scraper#26]
I followed every step on the main page but keep getting this error.

> Traceback (most recent call last):
>   File "/usr/local/bin/scrape-hltv.py", line 6, in <module>
>     exec(compile(open(__file__).read(), __file__, 'exec'))
>   File "/root/HLTV-Scraper-master/scripts/scrape-hltv.py", line 21
>     print(f"\nBeginning test scrape for {match_id[0]}:\n")
>                                                         ^
> SyntaxError: invalid syntax
> 

I am sorry if this is simple but Python is not my main language so not sure if I am missing something

**Comment by ReagentX** [comment]
Which version of python are you using? This library requires you use Python 3.6.3.

**Comment by CodingAkiraZi** [comment]
I followed the Ask Ubuntu on installing Python 3.6.3. is there something else I need to do so only Python 3 runs rather then the version that comes with the OS?

**Comment by ReagentX** [comment]
`sudo apt-get install python3`

then, instead of `python script.py`, run

`python3 script.py`

**Comment by CodingAkiraZi** [comment]
there must be something wrong with the package I downloaded or something, will make new VM and try from bare bones install
