### ISSUE TITLE
match/ban picks

### ISSUE THREAD

**Issue by kpei** [ReagentX/HLTV-Scraper#4]
It'd be awesome to have a dataset for scraped pick/bans of each match along with selection type if applicable

Example [row](https://i.imgur.com/B9fQAbk.png):

match id, team 1, team 2, team 1 ban 1, team 1 ban 2, team 1 pick 1, team 2 ban 1, team 2 ban 2, team 2 pick 1, random, bp type
1, misfits, nrg, de_cbble, de_train, de_nuke, de_cache, de_overpass, de_inferno, de_mirage, 'bbppbbr'

team order and bp_type should imply order in which it was picked and banned.

**Comment by ReagentX** [comment]
Do you have any suggestions as to how I should organize the CSV files? This is not as straightforward as tabulating player stats.

**Comment by ReagentX** [comment]
I'm thinking for more expandable sets I should structure like this:

|Match ID | Team | Pick # | Type | Map
|--|--|--|--|--
| Match ID ###### | 1234 | Remove 1 | Nuke

**Comment by kpei** [comment]
That is a more flexible and better format (accommodates bo5s/1s).

**Comment by ReagentX** [comment]
Added in [a754499](https://github.com/ReagentX/HLTV-Scraper/commit/a7544998bb321ea757889e7a2bcbb8573cd2ae19).
