### ISSUE TITLE
pickAndBans.csv should use team ID

### ISSUE THREAD

**Issue by kpei** [ReagentX/HLTV-Scraper#7]
let's stay consistent with the other files.

**Comment by ReagentX** [comment]
My original plan was to do this, but the way the parser works right now is it [looks at](https://github.com/ReagentX/HLTV-Scraper/blob/73338370b38fbaf4d79c1625df061fcc4155e704/scraper.py#L327) the `standard-box veto-box` element, which does not use Team IDs. If this is an issue that affects analysis I will do a lookup to the `teams.csv` file to get the ID, but if this does not affect analysis I would prefer to leave less room for error.

**Comment by kpei** [comment]
I think doing a simple join on teams.csv is fine, hltv is structured after all, the names will be consistent.

**Comment by ReagentX** [comment]
Fixed in `get_match_vetos` in [e4ae7cc](https://github.com/ReagentX/HLTV-Scraper/commit/e4ae7cc15fcaf0f721953bbe75eb5b0926e2afb7#diff-59a495c8378f4d741c5da171de1312bdR310)
